version: '3.8'

services:
  # API Service
  api:
    build: ./apps/api
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - app-network

  # Database (PostgreSQL)
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=yellow_ladder_coffee
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Web Application (optional, for production)
  web:
    build: ./apps/web
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
